services:
  db:
    image: postgres:16
    container_name: bikes_db
    environment:
      POSTGRES_DB: bikes_db
      POSTGRES_USER: bikes_user
      POSTGRES_PASSWORD: bikes_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
